version: "3"

services:
  front-end:
    image: node:18-slim
    container_name: ar-mysterygame-frontend
    ports:
      - "5173:5173"
      - "3100:3100"
    volumes:
      - ./:/ar-mysterygame/
    working_dir: /ar-mysterygame/
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true